# 예시: 인구, GDP, 이산화탄소 배출량
indicators = {
                'SP.POP.TOTL':'총 인구(명)', 
                'AG.LND.TOTL.K2':'면적(km2)',
                'SI.POV.NAHC':'국가 빈곤선 이하 인구 비율(%)',
                # 'SI.DST.FRST.20':'하위 20% 소득비중(%)',
                # 'SP.DYN.IMRT.IN':'유아사망률(명_1000명 출생아 기준)',
                # 'SE.PRM.ENRR':'초등학교 순등록율(%)',
                # 'SP.POP.GROW':'총 인구 성장률(연간 %)',
                # 'EN.POP.DNST':'인구 밀도(명_km2)',
                # 'NY.GNP.PCAP.CD':'1인당 GNI(현재 US $)',
                # 'SP.DYN.LE00.IN':'기대수명(년)',
                # 'SH.IMM.MEAS':'홍역 예방접종 비율(%, 12-23개월 유아 기준)',
                # 'SH.DYN.AIDS.ZS':'HIV_AIDS 발병율(%, 15-49세 기준)',
                # 'ER.PTD.TOTL.ZS':'육상 및 해양 보존 지역 비율(%, 총 영토기준)',
                # 'SP.URB.GROW':'도시 인구 증가율(연간 %)',
                # 'EN.ATM.CO2E.PC':'이산화탄소 배출량(1인당 미터 톤)',
                # 'ER.H2O.FWTL.ZS':'연간 담수인출(%, 총 국토 내 가용자원 기준)',
                # 'SH.STA.SMSS.ZS':'향상된 위생시설 접근가능 인구 비율(%, 총 접근가능 인구기준)',
                # 'EG.USE.PCAP.KG.OE':'에너지 이용량(1인당 석유환산톤)',
                # 'EG.USE.ELEC.KH.PC':'전기 소비량(1인당 kWh)',
                # 'NY.GDP.MKTP.CD':'GDP(현재 US $)',
                # 'NV.AGR.TOTL.ZS':'농업의 GDP 기여도(%)',
                # 'NV.SRV.TOTL.ZS':'서비스업의 GDP 기여도(%)',
                # 'NE.IMP.GNFS.ZS':'재화 및 용역 수입(GDP 대비 %)',
                # 'GC.NLD.TOTL.GD.ZS':'순 대출_순 차입(GDP 대비 %)',
                # 'GC.TAX.TOTL.GD.ZS':'세수(GDP 대비 %)',
                # 'IT.NET.USER.ZS':'인터넷 사용 인구(%)',
                # 'TG.VAL.TOTL.GD.ZS':'상품 무역(GDP 대비 %)',
                # 'BX.KLT.DINV.CD.WD':'FDI순유입(BoP, 현재 US $)',
                # '6.0.GDP_growth':'GDP 증가율(연간 %)',
                # 'NV.IND.TOTL.ZS':'산업의 GDP 기여도(%)',
                # 'NE.EXP.GNFS.ZS':'재화 및 용역 수출(GDP 대비 %)',
                # 'GC.REV.XGRT.GD.ZS':'수익, 보조금제외(GDP 대비 %)',
                # 'IC.REG.DURS':'사업을 시작하기까지 걸리는 시간(일)',
                # 'IT.CEL.SETS.P2':'인구 100명당 휴대폰 가입자(100명 당)',
                # 'TX.VAL.TECH.MANF.ZS':'하이테크 수출(수출제조품 대비 %)',
                # 'DT.DOD.DECT.CD':'총 외채(DOD, 현재 US $)',
                # 'DT.ODA.ODAT.CD':'순공적원조 수혜량(현재 US $)'
}